changelog-seen = 2

[llvm]
download-ci-llvm = true

[rust]
incremental = true
codegen-units = 0
use-lld = true
deny-warnings = false

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[build]
# extended = true
# vendor = true
# tools = ["rust-analyzer"]
